
-- ============================================================
-- 4. zi_entities
--    Legal business entity. One entity, multiple products + branches.
--    Business Code: ZE prefix → ZEA01, ZEB01...
-- ============================================================
CREATE TABLE zi_entities (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code               TEXT UNIQUE NOT NULL,       -- ZEA01 (generated by app)
  legal_name            TEXT NOT NULL,              -- registered legal name
  trade_name            TEXT,                       -- doing business as (DBA)
  entity_type           TEXT NOT NULL,              -- sole_proprietor | company | partnership | trust | individual
  country_code          TEXT NOT NULL DEFAULT 'IN',
  business_id_type      TEXT,                       -- gst | cin | msme | ein | uen | trade_license
  business_id_hash      TEXT,                       -- SHA256
  business_id_last6     TEXT,                       -- display only
  business_id_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  city                  TEXT,
  state                 TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_entity_type CHECK (
    entity_type IN ('sole_proprietor','company','partnership','trust','individual')
  )
);
ss