
-- ============================================================
-- 1. zi_individuals
--    One record per real human. Permanent. Never deleted.
--    Business Code: ZU prefix → ZUA01, ZUB01...
-- ============================================================
CREATE TABLE zi_individuals (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code               TEXT UNIQUE NOT NULL,       -- ZUA01 (generated by app)
  display_name          TEXT NOT NULL,
  country_code          TEXT NOT NULL DEFAULT 'IN', -- ISO 3166-1 alpha-2
  national_id_type      TEXT,                       -- aadhaar, ssn, nric, emirates_id...
  national_id_hash      TEXT,                       -- SHA256, never raw
  national_id_last6     TEXT,                       -- last 6 digits for display only
  national_id_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  auth_user_id          UUID UNIQUE,                -- Supabase auth.users.id
  avatar_url            TEXT,
  preferred_lang        TEXT NOT NULL DEFAULT 'en',
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at          TIMESTAMPTZ
);