// ─── Ziort Landing Page Product Registry ───────────────────────────────────
// Full details for all 19 products used across LandingPage + ProductPage

export interface ProductFeature {
  title: string
  desc:  string
  icon:  string
}

export interface LandingProduct {
  code:         string
  slug:         string
  name:         string
  emoji:        string
  abbr:         string
  tagline:      string
  headline:     string
  subheadline:  string
  desc:         string
  badge?:       string
  isLive?:      boolean
  color:        string
  glow:         string
  accent:       string
  textAccent:   string
  bgAccent:     string
  borderAccent: string
  features:     ProductFeature[]
  forWhom:      { who: string; icon: string; desc: string }[]
  steps:        { n: number; title: string; desc: string }[]
  stats:        { label: string; value: string }[]
}

export const LANDING_PRODUCTS: LandingProduct[] = [
  {
    code: 'ZPN', slug: 'zipawn', name: 'ZiPawn', emoji: '⚖️', abbr: 'ZP',
    tagline: 'Smart Pawn Shop Management',
    headline: 'Run Your Pawn Shop Digitally',
    subheadline: 'Digital tickets, live gold rates, loan tracking & overdue alerts — built for Indian pawnbrokers.',
    desc: 'ZiPawn is a complete digital pawn shop management system. Issue pawn tickets, valuate gold & jewellery in real-time, track loan lifecycles, collect interest and get overdue alerts — all from one screen.',
    badge: 'Most Popular', isLive: true,
    color: 'from-indigo-500 to-violet-600',
    glow: 'rgba(109,106,222,0.35)', accent: '#6d6ade',
    textAccent: 'text-indigo-400', bgAccent: 'bg-indigo-500/10', borderAccent: 'border-indigo-500/20',
    features: [
      { icon: '🎫', title: 'Digital Pawn Tickets', desc: 'Issue, print and manage pawn tickets with QR codes instantly.' },
      { icon: '🥇', title: 'Live Gold Valuation', desc: 'Real-time gold & silver rates to value jewellery accurately.' },
      { icon: '📊', title: 'Loan Lifecycle', desc: 'Track active, renewed, overdue and closed loans in one dashboard.' },
      { icon: '🔔', title: 'Overdue Alerts', desc: 'Automated SMS & app alerts for overdue loans before they lapse.' },
      { icon: '👥', title: 'Customer Management', desc: 'Store KYC, Aadhaar-linked customer profiles with loan history.' },
      { icon: '🧾', title: 'GST Receipts', desc: 'Print GST-compliant receipts and interest certificates instantly.' },
    ],
    forWhom: [
      { who: 'Pawnbrokers', icon: '🏪', desc: 'Run your pawn shop paperlessly — from pledge to redemption.' },
      { who: 'Jewellery Shops', icon: '💍', desc: 'Offer gold loans with live rate valuation and proper documentation.' },
      { who: 'NBFC / Finance Companies', icon: '🏦', desc: 'Manage multiple branches of gold loan portfolios centrally.' },
    ],
    steps: [
      { n: 1, title: 'Add Customer & Items', desc: 'Search or create a customer, scan Aadhaar, enter pledged jewellery details.' },
      { n: 2, title: 'Value & Issue Ticket', desc: 'System calculates loan value at live gold rate. Print the pawn ticket.' },
      { n: 3, title: 'Track & Collect', desc: 'Monitor loan status, collect interest, renew or close loans easily.' },
    ],
    stats: [{ value: '3,000+', label: 'Pawnbrokers' }, { value: '₹2 Cr+', label: 'Daily Loans' }, { value: '15s', label: 'Ticket Issue Time' }],
  },
  {
    code: 'ZSHP', slug: 'zishop', name: 'ZiShop', emoji: '🛒', abbr: 'ZS',
    tagline: 'Retail POS & Inventory',
    headline: 'Power Your Shop with Smart POS',
    subheadline: 'Smart billing, live inventory, udhaar book, GST reports — for kirana, jewellery & every retailer.',
    desc: 'ZiShop is the complete retail management platform. Run billing on any device, manage inventory in real-time, track credit sales in your digital udhaar book, and generate instant GST reports.',
    color: 'from-amber-500 to-orange-500',
    glow: 'rgba(245,158,11,0.3)', accent: '#f59e0b',
    textAccent: 'text-amber-400', bgAccent: 'bg-amber-500/10', borderAccent: 'border-amber-500/20',
    features: [
      { icon: '🖥️', title: 'Smart POS Billing', desc: 'Fast billing with barcode scanner support, discounts and returns.' },
      { icon: '📦', title: 'Live Inventory', desc: 'Real-time stock tracking with low-stock alerts and auto reorder.' },
      { icon: '📓', title: 'Udhaar Book', desc: 'Digital credit book to track who owes you and remind them automatically.' },
      { icon: '🧮', title: 'GST Reports', desc: 'GSTR-1, GSTR-3B and HSN summary reports ready to file.' },
      { icon: '🛍️', title: 'Purchase Orders', desc: 'Create POs, receive stock and auto-update inventory.' },
      { icon: '📱', title: 'Works Offline', desc: 'Continue billing even without internet. Syncs when connected.' },
    ],
    forWhom: [
      { who: 'Kirana / General Stores', icon: '🏪', desc: 'Manage thousands of items, run fast billing at the counter.' },
      { who: 'Jewellery Shops', icon: '💎', desc: 'Handle complex jewellery billing with making charges and wastage.' },
      { who: 'Clothing & Textile', icon: '👕', desc: 'Manage size/colour variants, season stock and customer orders.' },
    ],
    steps: [
      { n: 1, title: 'Add Products & Prices', desc: 'Import your product catalogue or add items with barcode, HSN, price.' },
      { n: 2, title: 'Scan & Bill', desc: 'Scan barcode or search product, apply discount, collect payment.' },
      { n: 3, title: 'Track & Report', desc: 'Check daily sales, stock movement, udhaar dues and GST summary.' },
    ],
    stats: [{ value: '1,200+', label: 'Shops' }, { value: '50K+', label: 'Bills/Day' }, { value: '2 sec', label: 'Average Bill Time' }],
  },
  {
    code: 'ZLDG', slug: 'ziledger', name: 'ZiLedger', emoji: '📒', abbr: 'ZL',
    tagline: 'Accounting & Bookkeeping',
    headline: 'Your Complete GST Accounting Solution',
    subheadline: 'GST invoices, payment tracking, expense journals and P&L — all in one ledger.',
    desc: 'ZiLedger brings full double-entry bookkeeping to small businesses without the complexity. Create GST invoices, record expenses, manage accounts payable/receivable and get P&L at a glance.',
    color: 'from-indigo-500 to-violet-500',
    glow: 'rgba(99,102,241,0.3)', accent: '#6366f1',
    textAccent: 'text-indigo-400', bgAccent: 'bg-indigo-500/10', borderAccent: 'border-indigo-500/20',
    features: [
      { icon: '🧾', title: 'GST Invoices', desc: 'Create B2B, B2C, export and RCM invoices with auto tax calculation.' },
      { icon: '💸', title: 'Payment Tracking', desc: 'Record payments against invoices, track outstanding and advances.' },
      { icon: '📊', title: 'P&L Statement', desc: 'Real-time Profit & Loss report with month-on-month comparison.' },
      { icon: '📁', title: 'Expense Journal', desc: 'Record business expenses by category for tax deduction tracking.' },
      { icon: '👥', title: 'Parties & Ledgers', desc: 'Manage customer and supplier ledgers with statement views.' },
      { icon: '📤', title: 'GSTR Filing', desc: 'Export GSTR-1 and 3B data directly to the GST portal format.' },
    ],
    forWhom: [
      { who: 'Small Traders', icon: '🏪', desc: 'Replace messy cash books with organized digital ledgers.' },
      { who: 'Service Businesses', icon: '⚙️', desc: 'Track project billing, advances and outstanding collections.' },
      { who: 'Accountants', icon: '🧑‍💼', desc: 'Manage multiple client books and generate audit-ready reports.' },
    ],
    steps: [
      { n: 1, title: 'Setup Your Business', desc: 'Add GSTIN, business details, opening balances and bank accounts.' },
      { n: 2, title: 'Record Transactions', desc: 'Create invoices, record expenses, log payments — all categorized.' },
      { n: 3, title: 'Analyse & File', desc: 'View P&L, balance sheet, GST summaries. Export for filing.' },
    ],
    stats: [{ value: '800+', label: 'Businesses' }, { value: '₹500 Cr+', label: 'Invoices Processed' }, { value: '100%', label: 'GST Compliant' }],
  },
  {
    code: 'ZCLC', slug: 'zicalc', name: 'ZiCalc', emoji: '🧮', abbr: 'ZC',
    tagline: 'Financial Calculators Suite',
    headline: 'Every Financial Calculation in One App',
    subheadline: 'Interest, SIP, EMI, GST, gold value, date difference — 25+ calculators, always free.',
    desc: 'ZiCalc is your go-to financial calculator suite. No signup required. Calculate EMI, simple & compound interest, SIP returns, gold valuation, GST amounts, invoice totals and much more — instantly.',
    color: 'from-slate-500 to-gray-600',
    glow: 'rgba(100,116,139,0.3)', accent: '#94a3b8',
    textAccent: 'text-slate-400', bgAccent: 'bg-slate-500/10', borderAccent: 'border-slate-500/20',
    features: [
      { icon: '💰', title: 'Interest Calculators', desc: 'Simple interest, compound interest with monthly/quarterly compounding.' },
      { icon: '📈', title: 'SIP / Investment', desc: 'Calculate SIP returns, lumpsum growth and inflation-adjusted values.' },
      { icon: '🏠', title: 'EMI Calculator', desc: 'Home loan, vehicle loan EMI with full amortization schedule.' },
      { icon: '🥇', title: 'Gold Valuation', desc: 'Calculate gold value at live rates by weight and purity (24K/22K/18K).' },
      { icon: '🧾', title: 'GST Calculator', desc: 'Add/remove GST, split CGST & SGST, calculate reverse charge.' },
      { icon: '📅', title: 'Date & Time', desc: 'Calculate days between dates, due dates, age and working days.' },
    ],
    forWhom: [
      { who: 'Finance Professionals', icon: '👨‍💼', desc: 'Quick calculations during client meetings without Excel.' },
      { who: 'Shop Owners', icon: '🏪', desc: 'Calculate GST, gold value and interest at the counter instantly.' },
      { who: 'Students & Individuals', icon: '🎓', desc: 'Plan investments, compare loan options and understand returns.' },
    ],
    steps: [
      { n: 1, title: 'Choose Calculator', desc: 'Pick from 25+ calculators — no signup, no downloads.' },
      { n: 2, title: 'Enter Values', desc: 'Type in your numbers. Results update instantly as you type.' },
      { n: 3, title: 'Save & Share', desc: 'Copy result, share via WhatsApp or download as PDF.' },
    ],
    stats: [{ value: '25+', label: 'Calculators' }, { value: 'Free', label: 'Always' }, { value: '1M+', label: 'Calculations/Month' }],
  },
  {
    code: 'ZRCP', slug: 'zireceipt', name: 'ZiReceipt', emoji: '🧾', abbr: 'ZR',
    tagline: 'Digital Receipt Generator',
    headline: 'Professional Receipts in Seconds',
    subheadline: 'Create, print and download branded receipts instantly. No signup required.',
    desc: 'ZiReceipt lets anyone create professional digital receipts in seconds. Add your logo, business name, items, taxes and print or download PDF instantly. Multiple receipt types for every transaction.',
    color: 'from-orange-500 to-red-500',
    glow: 'rgba(249,115,22,0.3)', accent: '#f97316',
    textAccent: 'text-orange-400', bgAccent: 'bg-orange-500/10', borderAccent: 'border-orange-500/20',
    features: [
      { icon: '🎨', title: 'Custom Branding', desc: 'Add logo, business name, address and signature to receipts.' },
      { icon: '💵', title: 'Multiple Types', desc: 'Cash receipts, advance receipts, rent receipts, payment receipts.' },
      { icon: '🧮', title: 'Tax Support', desc: 'Add GST (CGST/SGST/IGST), TDS and other deductions.' },
      { icon: '📄', title: 'PDF Download', desc: 'Download as PDF or print directly from the browser.' },
      { icon: '📲', title: 'Share on WhatsApp', desc: 'Send receipt PDF directly via WhatsApp in one click.' },
      { icon: '📚', title: 'Receipt History', desc: 'Signup to save and access all past receipts anytime.' },
    ],
    forWhom: [
      { who: 'Landlords', icon: '🏠', desc: 'Generate rent receipts for tenants instantly every month.' },
      { who: 'Freelancers', icon: '💻', desc: 'Issue payment receipts to clients for services rendered.' },
      { who: 'Small Shops', icon: '🏪', desc: 'Give customers proper receipts without installing any software.' },
    ],
    steps: [
      { n: 1, title: 'Open ZiReceipt', desc: 'No login needed. Open the tool directly from any browser.' },
      { n: 2, title: 'Fill Details', desc: 'Add your business info, customer, items and amount in seconds.' },
      { n: 3, title: 'Download & Share', desc: 'Download PDF or share directly via WhatsApp link.' },
    ],
    stats: [{ value: 'Free', label: 'No Signup Needed' }, { value: '500K+', label: 'Receipts Generated' }, { value: '<10s', label: 'Time to Create' }],
  },
  {
    code: 'ZNVC', slug: 'ziinvoice', name: 'ZiInvoice', emoji: '📄', abbr: 'ZI',
    tagline: 'GST Invoicing & Tracking',
    headline: 'GST Invoices That Get Paid Faster',
    subheadline: 'Professional invoices with 9 types, payment tracking and WhatsApp delivery.',
    desc: 'ZiInvoice makes GST billing simple. Create tax invoices, proforma invoices, debit/credit notes and more. Track payment status, send payment reminders and get paid faster.',
    color: 'from-violet-500 to-indigo-600',
    glow: 'rgba(139,92,246,0.3)', accent: '#7c3aed',
    textAccent: 'text-violet-400', bgAccent: 'bg-violet-500/10', borderAccent: 'border-violet-500/20',
    features: [
      { icon: '📝', title: '9 Invoice Types', desc: 'Tax, proforma, export, RCM, debit note, credit note and more.' },
      { icon: '🔄', title: 'Payment Status', desc: 'Mark invoices as paid, partial or pending with due date alerts.' },
      { icon: '📲', title: 'WhatsApp Delivery', desc: 'Send invoice PDF to customer on WhatsApp in one tap.' },
      { icon: '🎨', title: 'Custom Templates', desc: 'Choose from professional templates and add your logo.' },
      { icon: '🔁', title: 'Recurring Invoices', desc: 'Set up auto-repeating invoices for subscriptions and retainers.' },
      { icon: '📊', title: 'Revenue Reports', desc: 'See monthly billing, top customers and outstanding dues.' },
    ],
    forWhom: [
      { who: 'Freelancers & Consultants', icon: '💼', desc: 'Send professional invoices and track payment from clients.' },
      { who: 'Service Businesses', icon: '⚙️', desc: 'Bill monthly retainers, project milestones and one-time work.' },
      { who: 'Manufacturers & Traders', icon: '🏭', desc: 'Create B2B tax invoices with HSN codes and GST breakdowns.' },
    ],
    steps: [
      { n: 1, title: 'Create Invoice', desc: 'Pick invoice type, add items with HSN, quantity and rate.' },
      { n: 2, title: 'Send to Customer', desc: 'Email or WhatsApp the PDF invoice instantly.' },
      { n: 3, title: 'Track & Remind', desc: 'Get notified of overdue invoices and send auto-reminders.' },
    ],
    stats: [{ value: '9', label: 'Invoice Types' }, { value: '100%', label: 'GST Compliant' }, { value: '2x', label: 'Faster Collections' }],
  },
  {
    code: 'ZQT', slug: 'ziquote', name: 'ZiQuote', emoji: '📋', abbr: 'ZQ',
    tagline: 'Quotations & Proposals',
    headline: 'Win More Deals with Better Quotes',
    subheadline: 'Professional quotations with client approval, e-signature and one-click invoice conversion.',
    desc: 'ZiQuote helps businesses close deals faster. Send beautiful quotations, collect client approval digitally, and convert accepted quotes to invoices instantly — no re-entry required.',
    color: 'from-amber-400 to-yellow-500',
    glow: 'rgba(245,158,11,0.3)', accent: '#f59e0b',
    textAccent: 'text-amber-400', bgAccent: 'bg-amber-500/10', borderAccent: 'border-amber-500/20',
    features: [
      { icon: '📋', title: 'Smart Templates', desc: 'Professional quote templates for services, products and projects.' },
      { icon: '✅', title: 'Digital Approval', desc: 'Client approves or rejects quote online without printing.' },
      { icon: '🔄', title: 'Convert to Invoice', desc: 'Accepted quote converts to invoice in one click — zero re-entry.' },
      { icon: '⏱️', title: 'Validity & Expiry', desc: 'Set validity periods. Get notified when quotes are expiring.' },
      { icon: '📊', title: 'Quote Analytics', desc: 'Track acceptance rate, pending quotes and won deals.' },
      { icon: '💬', title: 'Client Comments', desc: 'Clients can comment on specific line items before approving.' },
    ],
    forWhom: [
      { who: 'Contractors & Builders', icon: '🏗️', desc: 'Send detailed project quotes with terms and payment schedule.' },
      { who: 'IT & Software Companies', icon: '💻', desc: 'Quote projects, subscriptions and maintenance contracts.' },
      { who: 'Event Management', icon: '🎉', desc: 'Itemize events, get client sign-off before execution.' },
    ],
    steps: [
      { n: 1, title: 'Create Quote', desc: 'Add items, quantities, discounts and terms from your template.' },
      { n: 2, title: 'Send for Approval', desc: 'Client receives a link to review and approve online.' },
      { n: 3, title: 'Invoice Instantly', desc: 'On approval, generate invoice in one click.' },
    ],
    stats: [{ value: '40%', label: 'Faster Closing' }, { value: '0', label: 'Re-entry of Data' }, { value: '85%', label: 'Approval Rate' }],
  },
  {
    code: 'ZSCN', slug: 'ziscan', name: 'ZiScan', emoji: '🔍', abbr: 'ZSC',
    tagline: 'Document Scanning & OCR',
    headline: 'Turn Paper into Digital Data Instantly',
    subheadline: 'AI-powered OCR scans bills, invoices, Aadhaar and converts them to editable data.',
    desc: 'ZiScan uses AI OCR to extract text and data from paper documents, bills and ID cards. Scan receipts for expense entry, invoices for payment processing, or Aadhaar for customer KYC — all automated.',
    color: 'from-violet-400 to-fuchsia-500',
    glow: 'rgba(167,139,250,0.3)', accent: '#a78bfa',
    textAccent: 'text-violet-400', bgAccent: 'bg-violet-500/10', borderAccent: 'border-violet-500/20',
    features: [
      { icon: '📷', title: 'Camera Scan', desc: 'Point your phone camera at any document for instant scanning.' },
      { icon: '🤖', title: 'AI OCR Engine', desc: 'Extract text, numbers and tables from any printed document.' },
      { icon: '🪪', title: 'KYC / Aadhaar Scan', desc: 'Extract customer details from Aadhaar and PAN cards.' },
      { icon: '📄', title: 'Bill Processing', desc: 'Scan vendor bills and auto-fill expense entry forms.' },
      { icon: '🔍', title: 'Invoice Matching', desc: 'Match scanned invoice data against your purchase orders.' },
      { icon: '📁', title: 'Multi-Format Export', desc: 'Export scanned data as CSV, JSON or structured PDF.' },
    ],
    forWhom: [
      { who: 'Accountants', icon: '🧑‍💼', desc: 'Scan and auto-import hundreds of vendor bills for entry.' },
      { who: 'Pawnbrokers', icon: '⚖️', desc: 'Scan customer Aadhaar and PAN for instant KYC during pledging.' },
      { who: 'Office Managers', icon: '🏢', desc: 'Digitize paper records and searchable archives without manual typing.' },
    ],
    steps: [
      { n: 1, title: 'Scan Document', desc: 'Use your phone camera or upload an existing image/PDF.' },
      { n: 2, title: 'AI Extracts Data', desc: 'Our OCR engine identifies and extracts all text and numbers.' },
      { n: 3, title: 'Review & Export', desc: 'Verify extracted data, edit if needed, export or auto-fill forms.' },
    ],
    stats: [{ value: '99%', label: 'OCR Accuracy' }, { value: '3s', label: 'Scan Time' }, { value: '15+', label: 'Document Types' }],
  },
  {
    code: 'ZPST', slug: 'zipost', name: 'ZiPost', emoji: '📢', abbr: 'ZPT',
    tagline: 'Hyperlocal Classifieds & Listings',
    headline: 'Post Free Ads. Find Local Deals.',
    subheadline: 'Buy, sell and rent locally. Post free classifieds for gold, property, vehicles and more.',
    desc: 'ZiPost is a free hyperlocal classifieds platform for Indian SMBs and individuals. Post buy/sell ads for gold, jewellery, vehicles, electronics and property. Browse local listings without signup.',
    color: 'from-fuchsia-500 to-pink-500',
    glow: 'rgba(217,70,239,0.3)', accent: '#d946ef',
    textAccent: 'text-fuchsia-400', bgAccent: 'bg-fuchsia-500/10', borderAccent: 'border-fuchsia-500/20',
    features: [
      { icon: '📢', title: 'Free Listings', desc: 'Post ads for free. No hidden charges ever.' },
      { icon: '📍', title: 'Hyperlocal', desc: 'Reach buyers and sellers in your city, district or pincode.' },
      { icon: '🔍', title: 'Browse Without Signup', desc: 'Anyone can browse listings without creating an account.' },
      { icon: '⚡', title: 'Post in Minutes', desc: 'Create a listing with photos and price in under 2 minutes.' },
      { icon: '💬', title: 'WhatsApp Connect', desc: 'Interested buyers contact you directly via WhatsApp.' },
      { icon: '⭐', title: 'Featured Listings', desc: 'Boost your ad for more visibility at low cost.' },
    ],
    forWhom: [
      { who: 'Gold & Jewellery Sellers', icon: '💍', desc: 'Post second-hand gold, jewellery and watches for local buyers.' },
      { who: 'Vehicle Owners', icon: '🚗', desc: 'Sell used vehicles fast to verified local buyers.' },
      { who: 'Property Owners', icon: '🏠', desc: 'List rooms, houses and shops for rent or sale locally.' },
    ],
    steps: [
      { n: 1, title: 'Choose Category', desc: 'Select from gold, vehicle, property, electronics and more.' },
      { n: 2, title: 'Add Photos & Price', desc: 'Upload clear photos, set your price and description.' },
      { n: 3, title: 'Get Inquiries', desc: 'Interested buyers reach you via WhatsApp or call.' },
    ],
    stats: [{ value: 'Free', label: 'Always Free to Post' }, { value: '50K+', label: 'Active Listings' }, { value: '200+', label: 'Cities Covered' }],
  },
  {
    code: 'ZFLT', slug: 'zifleet', name: 'ZiFleet', emoji: '🚛', abbr: 'ZF',
    tagline: 'Fleet & Vehicle Management',
    headline: 'Manage Your Fleet Like a Pro',
    subheadline: 'Track vehicles, trips and drivers in real-time. Fuel logs, maintenance and compliance — unified.',
    desc: 'ZiFleet is the complete fleet management platform for transport businesses. Track vehicles in real-time, manage drivers, log trips, monitor fuel consumption, schedule maintenance and stay compliant.',
    color: 'from-cyan-500 to-sky-600',
    glow: 'rgba(6,182,212,0.3)', accent: '#06b6d4',
    textAccent: 'text-cyan-400', bgAccent: 'bg-cyan-500/10', borderAccent: 'border-cyan-500/20',
    features: [
      { icon: '📍', title: 'Live Tracking', desc: 'Real-time GPS tracking for all vehicles on one map.' },
      { icon: '🗺️', title: 'Trip Management', desc: 'Assign trips, track start/end, log distances and tolls.' },
      { icon: '⛽', title: 'Fuel Logs', desc: 'Record fuel fills, track consumption per vehicle per route.' },
      { icon: '👤', title: 'Driver Records', desc: 'Manage driver profiles, licenses, attendance and performance.' },
      { icon: '🔧', title: 'Maintenance Schedule', desc: 'Service reminders, repair logs and cost tracking per vehicle.' },
      { icon: '📑', title: 'Compliance Docs', desc: 'Track permit, insurance and fitness certificate expiry dates.' },
    ],
    forWhom: [
      { who: 'Transport Companies', icon: '🚛', desc: 'Manage a fleet of trucks, tankers or trailers efficiently.' },
      { who: 'School / Corporate Buses', icon: '🚌', desc: 'Track school or corporate buses with route and attendance.' },
      { who: 'Delivery Businesses', icon: '🛵', desc: 'Monitor last-mile delivery bikes and vans in real-time.' },
    ],
    steps: [
      { n: 1, title: 'Add Vehicles & Drivers', desc: 'Register fleet vehicles, assign drivers with license details.' },
      { n: 2, title: 'Assign & Track Trips', desc: 'Dispatch trips, track live location and monitor fuel usage.' },
      { n: 3, title: 'Reports & Compliance', desc: 'Get vehicle-wise cost reports and compliance alerts.' },
    ],
    stats: [{ value: '500+', label: 'Vehicles Managed' }, { value: '10K+', label: 'Trips Logged' }, { value: '18%', label: 'Avg Fuel Savings' }],
  },
  {
    code: 'ZLD', slug: 'ziload', name: 'ZiLoad', emoji: '📦', abbr: 'ZLD',
    tagline: 'Goods Transport & Logistics',
    headline: 'Connect Shippers with Trucks',
    subheadline: 'Post loads, find trucks and book transport across India on the open load board.',
    desc: 'ZiLoad is India\'s open load board marketplace. Shippers post loads, truck owners bid in real-time, and both parties get matched instantly. Manage bookings, e-way bills and payments on one platform.',
    color: 'from-teal-500 to-emerald-600',
    glow: 'rgba(20,184,166,0.3)', accent: '#14b8a6',
    textAccent: 'text-teal-400', bgAccent: 'bg-teal-500/10', borderAccent: 'border-teal-500/20',
    features: [
      { icon: '📋', title: 'Load Board', desc: 'Post loads with origin, destination, weight and timing instantly.' },
      { icon: '🤝', title: 'Bid & Match', desc: 'Truck owners bid on loads. Shippers select the best offer.' },
      { icon: '⚡', title: 'Instant Booking', desc: 'Confirm booking, generate LR and e-way bill digitally.' },
      { icon: '🛣️', title: 'Live Tracking', desc: 'Track shipment location in real-time until delivery.' },
      { icon: '💳', title: 'Digital Payments', desc: 'Advance and balance payments via UPI, NEFT directly in app.' },
      { icon: '⭐', title: 'Verified Network', desc: 'All transporters are verified with RC, license and GST.' },
    ],
    forWhom: [
      { who: 'Manufacturers & Traders', icon: '🏭', desc: 'Move goods without haggling — get competitive rates instantly.' },
      { who: 'Truck Owners', icon: '🚛', desc: 'Find loads for empty return trips. Never run empty again.' },
      { who: 'Logistics Brokers', icon: '🤝', desc: 'Build your digital brokerage on ZiLoad\'s platform.' },
    ],
    steps: [
      { n: 1, title: 'Post Your Load', desc: 'Add origin, destination, material, weight and requirement.' },
      { n: 2, title: 'Receive Bids', desc: 'Get bids from verified truck owners near your pickup point.' },
      { n: 3, title: 'Book & Track', desc: 'Confirm, generate documents and track until delivery.' },
    ],
    stats: [{ value: '200+', label: 'Active Routes' }, { value: '1,000+', label: 'Verified Trucks' }, { value: '30min', label: 'Avg Match Time' }],
  },
  {
    code: 'ZFD', slug: 'zifood', name: 'ZiFood', emoji: '🍽️', abbr: 'ZFD',
    tagline: 'Restaurant & Kitchen Management',
    headline: 'Run Your Restaurant on Autopilot',
    subheadline: 'Table management, KOT printing, kitchen display and daily reports — for any food business.',
    desc: 'ZiFood is the complete restaurant management system for dine-in, takeaway and delivery. Manage tables, send orders to kitchen digitally, track sales and generate end-of-day reports effortlessly.',
    color: 'from-red-500 to-orange-500',
    glow: 'rgba(239,68,68,0.3)', accent: '#ef4444',
    textAccent: 'text-red-400', bgAccent: 'bg-red-500/10', borderAccent: 'border-red-500/20',
    features: [
      { icon: '🍽️', title: 'Table Management', desc: 'Visual table map. Seat, merge, transfer and split tables easily.' },
      { icon: '🖨️', title: 'KOT Printing', desc: 'Kitchen Order Tickets print automatically on kitchen printer.' },
      { icon: '📺', title: 'Kitchen Display', desc: 'Smart KDS shows orders by priority with ready/served status.' },
      { icon: '💵', title: 'Fast Billing', desc: 'Bill splitting, discounts, GST and multiple payment modes.' },
      { icon: '📊', title: 'Daily Reports', desc: 'Sales summary, item-wise analysis and staff performance daily.' },
      { icon: '🛵', title: 'Delivery Orders', desc: 'Manage Swiggy, Zomato and direct delivery orders from one screen.' },
    ],
    forWhom: [
      { who: 'Restaurants & Cafes', icon: '☕', desc: 'Full dine-in management from table to bill to report.' },
      { who: 'Dhabas & QSR', icon: '🍛', desc: 'Fast-paced counter billing with kitchen display.' },
      { who: 'Cloud Kitchens', icon: '🏭', desc: 'Manage delivery orders across multiple platforms in one screen.' },
    ],
    steps: [
      { n: 1, title: 'Setup Tables & Menu', desc: 'Create your table layout and add menu items with prices.' },
      { n: 2, title: 'Take & Send Orders', desc: 'Waiters take orders on tablet. KOT prints in kitchen automatically.' },
      { n: 3, title: 'Bill & Report', desc: 'Settle bill, collect payment. See end-of-day report instantly.' },
    ],
    stats: [{ value: '400+', label: 'Restaurants' }, { value: '1M+', label: 'Orders Processed' }, { value: '60%', label: 'Less Paper Waste' }],
  },
  {
    code: 'ZCR', slug: 'zicare', name: 'ZiCare', emoji: '🏥', abbr: 'ZCR',
    tagline: 'Clinic & Patient Management',
    headline: 'Modern Healthcare for Every Clinic',
    subheadline: 'OPD queue, prescriptions, patient records and pharmacy billing — built for Indian healthcare.',
    desc: 'ZiCare is the complete clinic management system for doctors, hospitals and pharmacies. Manage OPD queues, write digital prescriptions, maintain patient histories and run your pharmacy on one platform.',
    color: 'from-teal-500 to-cyan-500',
    glow: 'rgba(20,184,166,0.3)', accent: '#14b8a6',
    textAccent: 'text-teal-400', bgAccent: 'bg-teal-500/10', borderAccent: 'border-teal-500/20',
    features: [
      { icon: '📋', title: 'OPD Queue', desc: 'Digital token system. Patients check in and wait without crowding.' },
      { icon: '💊', title: 'Digital Prescriptions', desc: 'Write prescriptions with drug database, dosage and instructions.' },
      { icon: '📁', title: 'Patient Records', desc: 'Complete EHR — visit history, vitals, tests and previous Rx.' },
      { icon: '🔬', title: 'Lab Integration', desc: 'Send test requests, receive reports and attach to patient files.' },
      { icon: '💰', title: 'Pharmacy Billing', desc: 'Integrated pharmacy with stock, expiry alerts and GST billing.' },
      { icon: '📅', title: 'Appointment Booking', desc: 'Online and walk-in appointment management for any specialty.' },
    ],
    forWhom: [
      { who: 'General Practitioners', icon: '👨‍⚕️', desc: 'Manage your daily OPD, prescriptions and patient records digitally.' },
      { who: 'Multi-Specialty Clinics', icon: '🏥', desc: 'Multiple doctors, departments and billing under one platform.' },
      { who: 'Pharmacists', icon: '💊', desc: 'Run your pharmacy with inventory, billing and prescription tracking.' },
    ],
    steps: [
      { n: 1, title: 'Patient Registration', desc: 'Register patient with UHID, add demographics and insurance.' },
      { n: 2, title: 'Consult & Prescribe', desc: 'Record vitals, write prescription digitally, order tests.' },
      { n: 3, title: 'Bill & Pharmacy', desc: 'Generate bill, dispense medicines from pharmacy inventory.' },
    ],
    stats: [{ value: '300+', label: 'Clinics' }, { value: '50K+', label: 'Patients Managed' }, { value: '0', label: 'Paper Prescriptions' }],
  },
  {
    code: 'ZYLD', slug: 'ziyield', name: 'ZiYield', emoji: '🌾', abbr: 'ZY',
    tagline: 'Farm & Agriculture Management',
    headline: 'Smart Farming Starts Here',
    subheadline: 'Track crops, expenses, mandi rates and sell produce — the complete agri management platform.',
    desc: 'ZiYield is built for Indian farmers and agribusinesses. Track farm plots, crop seasons, input costs, harvest yield and mandi rates. Access the agri marketplace to sell produce directly at better prices.',
    color: 'from-green-500 to-lime-500',
    glow: 'rgba(34,197,94,0.3)', accent: '#22c55e',
    textAccent: 'text-green-400', bgAccent: 'bg-green-500/10', borderAccent: 'border-green-500/20',
    features: [
      { icon: '🗺️', title: 'Farm Mapping', desc: 'Map your plots, track area, soil type and crop history.' },
      { icon: '🌱', title: 'Crop Calendar', desc: 'Plan sowing, irrigation, fertilizer and harvest dates season-wise.' },
      { icon: '💰', title: 'Input Cost Tracker', desc: 'Record seeds, fertilizers, labour and water costs per plot.' },
      { icon: '📊', title: 'Yield Records', desc: 'Log harvest quantity, quality grade and selling price per season.' },
      { icon: '📈', title: 'Mandi Rates', desc: 'Live mandi price for 500+ commodities across Indian APMCs.' },
      { icon: '🛒', title: 'Agri Marketplace', desc: 'Sell produce directly to buyers without middlemen.' },
    ],
    forWhom: [
      { who: 'Individual Farmers', icon: '👨‍🌾', desc: 'Track your crops, costs and get better prices for your produce.' },
      { who: 'FPOs & Cooperatives', icon: '🤝', desc: 'Aggregate member farm data and sell collectively.' },
      { who: 'Agri Input Dealers', icon: '🏪', desc: 'Manage stock, credit sales and farmer relationships.' },
    ],
    steps: [
      { n: 1, title: 'Map Your Farm', desc: 'Add fields, mark crop and soil details on the map.' },
      { n: 2, title: 'Log Crop Activities', desc: 'Record all activities, costs and observations throughout season.' },
      { n: 3, title: 'Sell at Best Price', desc: 'Check mandi rates and list produce on the marketplace.' },
    ],
    stats: [{ value: '2,000+', label: 'Farmers' }, { value: '50K acres', label: 'Under Management' }, { value: '30%', label: 'Better Returns' }],
  },
  {
    code: 'ZCHT', slug: 'zichit', name: 'ZiChit', emoji: '🪙', abbr: 'ZCH',
    tagline: 'Chit Fund & Savings Management',
    headline: 'Manage Chit Funds Digitally',
    subheadline: 'Run chit groups, pigmy savings, loans and field collection — for chit fund operators.',
    desc: 'ZiChit is the complete digital platform for chit fund companies and cooperative societies. Manage groups, track member payments, conduct auctions, disburse prizes and handle field agent collections.',
    badge: 'New',
    color: 'from-yellow-500 to-amber-500',
    glow: 'rgba(234,179,8,0.3)', accent: '#eab308',
    textAccent: 'text-yellow-400', bgAccent: 'bg-yellow-500/10', borderAccent: 'border-yellow-500/20',
    features: [
      { icon: '👥', title: 'Chit Groups', desc: 'Create and manage multiple chit groups with member enrollments.' },
      { icon: '🪙', title: 'Pigmy Savings', desc: 'Daily/weekly collection, passbook printing and savings tracking.' },
      { icon: '🏆', title: 'Auction Management', desc: 'Conduct monthly auctions, record bids and assign prizes.' },
      { icon: '💸', title: 'Loan Book', desc: 'Manage member loans, EMI collections and outstanding balances.' },
      { icon: '📱', title: 'Field Collection', desc: 'Agent mobile app for daily collection with GPS attendance.' },
      { icon: '📊', title: 'Group Reports', desc: 'Monthly statements, overdue tracking and commission reports.' },
    ],
    forWhom: [
      { who: 'Chit Fund Companies', icon: '🏢', desc: 'Manage multiple groups, members and regulatory compliance.' },
      { who: 'Cooperative Societies', icon: '🤝', desc: 'Savings, loans and member management in one platform.' },
      { who: 'Field Agents', icon: '🛵', desc: 'Collect installments, issue receipts and track on mobile.' },
    ],
    steps: [
      { n: 1, title: 'Create Chit Group', desc: 'Set group size, ticket value, duration and member names.' },
      { n: 2, title: 'Collect Monthly', desc: 'Mark installment payments, send reminders to defaulters.' },
      { n: 3, title: 'Auction & Disburse', desc: 'Conduct auction, announce prize winner and disburse amount.' },
    ],
    stats: [{ value: '150+', label: 'Chit Companies' }, { value: '10K+', label: 'Active Members' }, { value: '₹25 Cr+', label: 'Monthly Volume' }],
  },
  {
    code: 'ZBLD', slug: 'zibuild', name: 'ZiBuild', emoji: '🏗️', abbr: 'ZB',
    tagline: 'Real Estate & Construction',
    headline: 'Build More. Waste Less.',
    subheadline: 'Material procurement, project tracking and buyer management for construction businesses.',
    desc: 'ZiBuild is the digital hub for builders, contractors and real estate developers. Order materials from verified suppliers, track project progress, manage buyer bookings and stay on budget.',
    badge: 'New',
    color: 'from-orange-500 to-red-600',
    glow: 'rgba(249,115,22,0.3)', accent: '#f97316',
    textAccent: 'text-orange-400', bgAccent: 'bg-orange-500/10', borderAccent: 'border-orange-500/20',
    features: [
      { icon: '📦', title: 'Material Orders', desc: 'Order cement, steel, sand from verified local dealers online.' },
      { icon: '💰', title: 'Live Material Prices', desc: 'Compare prices from multiple suppliers in real-time.' },
      { icon: '🏗️', title: 'Project Tracking', desc: 'Track progress by stage, milestone and contractor.' },
      { icon: '🏘️', title: 'Buyer Management', desc: 'Manage flat bookings, payment schedules and demands.' },
      { icon: '🚚', title: 'Delivery Tracking', desc: 'Track material deliveries with digital DO and receipts.' },
      { icon: '📊', title: 'Project Budget', desc: 'Compare planned vs actual costs with variance reports.' },
    ],
    forWhom: [
      { who: 'Real Estate Developers', icon: '🏢', desc: 'Manage projects from procurement to buyer handover.' },
      { who: 'Contractors', icon: '👷', desc: 'Order materials digitally and track site-wise usage.' },
      { who: 'Material Dealers', icon: '🏭', desc: 'List your materials, receive orders and deliver efficiently.' },
    ],
    steps: [
      { n: 1, title: 'Create Project', desc: 'Add project details, phases, BOQ and timeline.' },
      { n: 2, title: 'Order Materials', desc: 'Compare suppliers, order materials, schedule delivery.' },
      { n: 3, title: 'Track & Sell', desc: 'Monitor progress, manage buyers and collect payments.' },
    ],
    stats: [{ value: '120+', label: 'Developers' }, { value: '₹50 Cr+', label: 'Material Orders' }, { value: '22%', label: 'Cost Savings' }],
  },
  {
    code: 'ZPRTN', slug: 'zipartner', name: 'ZiPartner', emoji: '🤝', abbr: 'ZN',
    tagline: 'Referral & Partner Network',
    headline: 'Earn by Growing Ziort',
    subheadline: 'Refer businesses, earn 20% commission monthly, get rewards — the Ziort affiliate program.',
    desc: 'ZiPartner is Ziort\'s referral and partner program. Refer businesses to any Ziort product, earn 20% commission on every payment they make, and grow your monthly recurring income.',
    color: 'from-green-400 to-emerald-500',
    glow: 'rgba(74,222,128,0.3)', accent: '#4ade80',
    textAccent: 'text-green-400', bgAccent: 'bg-green-500/10', borderAccent: 'border-green-500/20',
    features: [
      { icon: '💰', title: '20% Commission', desc: 'Earn 20% of every subscription payment from your referrals.' },
      { icon: '🔁', title: 'Monthly Recurring', desc: 'Earn as long as the business stays subscribed — forever.' },
      { icon: '📱', title: 'UPI Payouts', desc: 'Automatic monthly payouts directly to your UPI or bank.' },
      { icon: '🏆', title: 'Rank & Rewards', desc: 'Top partners get iPhone, car, holidays and special bonuses.' },
      { icon: '📊', title: 'Partner Dashboard', desc: 'Track referrals, conversions, earnings and payout history.' },
      { icon: '🎯', title: '19 Products to Sell', desc: 'Refer any of 19 Ziort products — more products, more income.' },
    ],
    forWhom: [
      { who: 'Accountants & CAs', icon: '🧑‍💼', desc: 'Refer your clients to Ziort and earn monthly commissions.' },
      { who: 'Tech Salespersons', icon: '💼', desc: 'Build a recurring income stream by selling software.' },
      { who: 'Business Consultants', icon: '📊', desc: 'Add Ziort to your consulting toolkit and earn referral fees.' },
    ],
    steps: [
      { n: 1, title: 'Join as Partner', desc: 'Sign up free. Get your unique referral link and partner kit.' },
      { n: 2, title: 'Refer Businesses', desc: 'Share your link with businesses that need Ziort products.' },
      { n: 3, title: 'Earn Every Month', desc: 'Earn 20% every time your referral pays. Month after month.' },
    ],
    stats: [{ value: '20%', label: 'Commission Rate' }, { value: '₹50K+', label: 'Avg Monthly Earning' }, { value: '∞', label: 'Earning Duration' }],
  },
  {
    code: 'ZPLS', slug: 'zipulse', name: 'ZiPulse', emoji: '⚡', abbr: 'ZPLS',
    tagline: 'CRM & Sales Pipeline',
    headline: 'Close More Deals. Faster.',
    subheadline: 'Lead tracking, sales pipeline, follow-up automation and team analytics for Indian sales teams.',
    desc: 'ZiPulse is a CRM built for Indian sales teams. Track leads from every source, manage your pipeline visually, automate follow-ups via WhatsApp/SMS, and never let a deal go cold again.',
    color: 'from-violet-500 to-purple-600',
    glow: 'rgba(139,92,246,0.3)', accent: '#8b5cf6',
    textAccent: 'text-violet-400', bgAccent: 'bg-violet-500/10', borderAccent: 'border-violet-500/20',
    features: [
      { icon: '🎯', title: 'Lead Capture', desc: 'Capture leads from web, Facebook, JD, WhatsApp in one inbox.' },
      { icon: '🗂️', title: 'Visual Pipeline', desc: 'Drag-drop Kanban pipeline from prospect to won deal.' },
      { icon: '🤖', title: 'Auto Follow-up', desc: 'Automated WhatsApp, SMS and email sequences for cold leads.' },
      { icon: '📊', title: 'Sales Analytics', desc: 'Conversion rates, pipeline velocity and rep performance.' },
      { icon: '📅', title: 'Activity Tracking', desc: 'Log calls, meetings and tasks. Never miss a follow-up.' },
      { icon: '🏆', title: 'Team Leaderboard', desc: 'Real-time leaderboard to motivate and compare sales reps.' },
    ],
    forWhom: [
      { who: 'Real Estate Sales Teams', icon: '🏘️', desc: 'Track site visits, follow-ups and booking conversions.' },
      { who: 'B2B Sales Teams', icon: '💼', desc: 'Manage enterprise deals with multi-stage pipeline.' },
      { who: 'Education & Edtech', icon: '🎓', desc: 'Manage admissions pipeline from inquiry to enrollment.' },
    ],
    steps: [
      { n: 1, title: 'Import Leads', desc: 'Connect your lead sources — web, Facebook, CSV or manual.' },
      { n: 2, title: 'Work Your Pipeline', desc: 'Move deals through stages, log activities, send follow-ups.' },
      { n: 3, title: 'Close & Analyse', desc: 'Win deals and review what\'s working in your pipeline.' },
    ],
    stats: [{ value: '250+', label: 'Sales Teams' }, { value: '3x', label: 'Conversion Uplift' }, { value: '40%', label: 'Less Lead Leakage' }],
  },
  {
    code: 'ZND', slug: 'zineed', name: 'ZiNeed', emoji: '🛍️', abbr: 'ZND',
    tagline: 'B2B Procurement Platform',
    headline: 'Smarter Business Procurement',
    subheadline: 'Send RFQs, compare supplier quotes and order digitally — the B2B buying platform for India.',
    desc: 'ZiNeed simplifies B2B procurement for Indian businesses. Send Request for Quotations to multiple suppliers, compare bids, approve and place orders — all in one digital workflow without WhatsApp chaos.',
    color: 'from-pink-500 to-rose-600',
    glow: 'rgba(236,72,153,0.3)', accent: '#ec4899',
    textAccent: 'text-pink-400', bgAccent: 'bg-pink-500/10', borderAccent: 'border-pink-500/20',
    features: [
      { icon: '📋', title: 'RFQ Management', desc: 'Send structured RFQs to multiple suppliers simultaneously.' },
      { icon: '⚖️', title: 'Quote Comparison', desc: 'Compare price, quality, delivery terms side by side.' },
      { icon: '✅', title: 'Digital Approval', desc: 'Multi-level PO approval workflow with audit trail.' },
      { icon: '📦', title: 'Order Tracking', desc: 'Track PO status from confirmation to delivery digitally.' },
      { icon: '🤝', title: 'Vendor Management', desc: 'Rate vendors, maintain approved vendor list and history.' },
      { icon: '💰', title: 'Spend Analytics', desc: 'Category-wise spend, savings and vendor performance reports.' },
    ],
    forWhom: [
      { who: 'Manufacturers', icon: '🏭', desc: 'Procure raw materials from multiple vendors efficiently.' },
      { who: 'Hospitality & Hotels', icon: '🏨', desc: 'Manage daily procurement of food, supplies and services.' },
      { who: 'Healthcare & Hospitals', icon: '🏥', desc: 'Streamline medical supply procurement with compliance.' },
    ],
    steps: [
      { n: 1, title: 'Create Purchase Request', desc: 'Raise a procurement need with specifications and quantity.' },
      { n: 2, title: 'Send RFQ & Compare', desc: 'Send to multiple vendors, receive bids, compare and select.' },
      { n: 3, title: 'Order & Track', desc: 'Raise PO, track delivery and rate the vendor on completion.' },
    ],
    stats: [{ value: '180+', label: 'Companies' }, { value: '5,000+', label: 'Vendors' }, { value: '28%', label: 'Avg Cost Savings' }],
  },
]

export const PRODUCT_MAP = new Map(LANDING_PRODUCTS.map(p => [p.slug, p]))

export const TRUST_PILLARS = [
  { icon: '☁️', title: 'Cloud Powered', desc: 'Access your data from any device, anywhere. Always in sync across all your team.' },
  { icon: '🔐', title: 'Bank-grade Security', desc: 'Row-level encryption. SOC 2 compliant. Only you see your business data.' },
  { icon: '🇮🇳', title: 'Built for India', desc: '₹ format, GST compliance, 8 Indian languages and every local business need.' },
  { icon: '💰', title: 'Start Free', desc: 'Free forever plan + 90-day full trial on every product. No credit card needed.' },
]
