// POST /api/v1/auth/register
// Creates a Supabase Auth user + zi_individuals record + default email row.
// Business code: ZU prefix, generated by fn_next_code().
import { db } from '@/ziorbitcore/db/client'
import { createClient } from '@supabase/supabase-js'
import { RegisterSchema } from '@/ziorbitcore/validators/auth'
import { nextIndividualCode } from '@/ziorbitcore/services/codes'
import { writeAudit, extractRequestMeta } from '@/ziorbitcore/services/audit'
import { sendWelcomeEmail } from '@/ziorbitcore/services/email'
import { created, validationError, conflict, serverError, badRequest } from '@/ziorbitcore/api/response'
import { withErrorHandler } from '@/ziorbitcore/api/response'
import crypto from 'crypto'

// Use service role to create users server-side
const adminAuth = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
)

export const POST = withErrorHandler(async (req: Request) => {
  const body = await req.json()
  const parsed = RegisterSchema.safeParse(body)
  if (!parsed.success) return validationError(parsed.error)

  const { display_name, email, password, country_code, preferred_lang } = parsed.data

  // Check if email already exists
  const { data: existing } = await db
    .from('zi_individual_emails')
    .select('id')
    .eq('email', email.toLowerCase())
    .eq('is_current', true)
    .maybeSingle()

  if (existing) return conflict('An account with this email already exists')

  // Create Supabase Auth user — auto-confirm so login works immediately.
  // Email verification is handled via the welcome email separately.
  const { data: authData, error: authError } = await adminAuth.auth.admin.createUser({
    email: email.toLowerCase(),
    password,
    email_confirm: true,
  })

  if (authError || !authData.user) {
    return badRequest(authError?.message ?? 'Failed to create auth user')
  }

  // Generate ZU code
  const zi_code = await nextIndividualCode()

  // Hash the email for privacy (not strictly needed but consistent with phone hashing)
  const email_hash = crypto.createHash('sha256').update(email.toLowerCase()).digest('hex')

  // Insert zi_individuals
  const { data: individual, error: indError } = await db
    .from('zi_individuals')
    .insert({
      zi_code,
      display_name,
      country_code,
      preferred_lang,
      auth_user_id: authData.user.id,
      is_active: true,
    })
    .select()
    .single()

  if (indError || !individual) {
    // Rollback: delete the auth user
    await adminAuth.auth.admin.deleteUser(authData.user.id)
    return serverError('Failed to create individual record', indError)
  }

  // Insert email record
  await db.from('zi_individual_emails').insert({
    individual_id: individual.id,
    email: email.toLowerCase(),
    is_current: true,
    is_verified: false,
  })

  // Audit
  const meta = extractRequestMeta(req)
  await writeAudit({
    action: 'CREATE',
    table_name: 'zi_individuals',
    record_id: individual.id,
    ref_code: zi_code,
    individual_id: individual.id,
    new_value: { zi_code, display_name, country_code },
    ...meta,
  })

  // Fire-and-forget welcome email
  sendWelcomeEmail({ to: email.toLowerCase(), displayName: display_name, ziCode: zi_code })

  return created({
    zi_code: individual.zi_code,
    display_name: individual.display_name,
    email: email.toLowerCase(),
    message: 'Account created. Please verify your email.',
  })
})
