-- ============================================================
-- Ziort — Migration 001: Core Schema
-- Tables: individuals, entities, branches, subscriptions,
--         memberships, biz_contacts, national_id_config
-- ============================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. zi_individuals
--    One record per real human. Permanent. Never deleted.
--    Business Code: ZU prefix → ZUA01, ZUB01...
-- ============================================================
CREATE TABLE zi_individuals (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code               TEXT UNIQUE NOT NULL,       -- ZUA01 (generated by app)
  display_name          TEXT NOT NULL,
  country_code          TEXT NOT NULL DEFAULT 'IN', -- ISO 3166-1 alpha-2
  national_id_type      TEXT,                       -- aadhaar, ssn, nric, emirates_id...
  national_id_hash      TEXT,                       -- SHA256, never raw
  national_id_last6     TEXT,                       -- last 6 digits for display only
  national_id_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  auth_user_id          UUID UNIQUE,                -- Supabase auth.users.id
  avatar_url            TEXT,
  preferred_lang        TEXT NOT NULL DEFAULT 'en',
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at          TIMESTAMPTZ
);

-- ============================================================
-- 2. zi_individual_emails
--    Email history — current + previous. Email never expires.
-- ============================================================
CREATE TABLE zi_individual_emails (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  individual_id     UUID NOT NULL REFERENCES zi_individuals(id),
  email             TEXT NOT NULL,
  is_current        BOOLEAN NOT NULL DEFAULT TRUE,
  is_verified       BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at       TIMESTAMPTZ,
  became_current_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  replaced_at       TIMESTAMPTZ,
  UNIQUE(individual_id, email)
);

CREATE INDEX idx_ind_emails_email ON zi_individual_emails(email);
CREATE INDEX idx_ind_emails_individual ON zi_individual_emails(individual_id);

-- ============================================================
-- 3. zi_individual_mobiles
--    Mobile history with recycling protection (12 month cooldown).
-- ============================================================
CREATE TABLE zi_individual_mobiles (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  individual_id     UUID NOT NULL REFERENCES zi_individuals(id),
  mobile_hash       TEXT NOT NULL UNIQUE,           -- SHA256 of full E.164 number
  mobile_last4      TEXT NOT NULL,                  -- last 4 digits for display
  country_dial_code TEXT NOT NULL,                  -- +91, +1, +971
  is_current        BOOLEAN NOT NULL DEFAULT TRUE,
  is_verified       BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at       TIMESTAMPTZ,
  became_current_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  replaced_at       TIMESTAMPTZ,
  cooldown_until    TIMESTAMPTZ                     -- replaced_at + 12 months
);

CREATE INDEX idx_ind_mobiles_hash ON zi_individual_mobiles(mobile_hash);
CREATE INDEX idx_ind_mobiles_individual ON zi_individual_mobiles(individual_id);

-- ============================================================
-- 4. zi_entities
--    Legal business entity. One entity, multiple products + branches.
--    Business Code: ZE prefix → ZEA01, ZEB01...
-- ============================================================
CREATE TABLE zi_entities (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code               TEXT UNIQUE NOT NULL,       -- ZEA01 (generated by app)
  legal_name            TEXT NOT NULL,              -- registered legal name
  trade_name            TEXT,                       -- doing business as (DBA)
  entity_type           TEXT NOT NULL,              -- sole_proprietor | company | partnership | trust | individual
  country_code          TEXT NOT NULL DEFAULT 'IN',
  business_id_type      TEXT,                       -- gst | cin | msme | ein | uen | trade_license
  business_id_hash      TEXT,                       -- SHA256
  business_id_last6     TEXT,                       -- display only
  business_id_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  city                  TEXT,
  state                 TEXT,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_entity_type CHECK (
    entity_type IN ('sole_proprietor','company','partnership','trust','individual')
  )
);

-- ============================================================
-- 5. zi_branches
--    Physical location or operational unit under an entity.
--    Business Code: ZBR prefix → ZBRA01
--    Reference Code: ZEA01ZBRA01 (globally unique)
-- ============================================================
CREATE TABLE zi_branches (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code       TEXT NOT NULL,                     -- ZBRA01 (unique within entity)
  entity_id     UUID NOT NULL REFERENCES zi_entities(id),
  ref_code      TEXT UNIQUE NOT NULL,              -- ZEA01ZBRA01 (globally unique)
  name          TEXT NOT NULL,
  address       TEXT,
  city          TEXT,
  state         TEXT,
  country_code  TEXT NOT NULL DEFAULT 'IN',
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,    -- head office flag
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, zi_code)
);

CREATE INDEX idx_branches_entity ON zi_branches(entity_id);

-- ============================================================
-- 6. zi_subscriptions
--    One row per entity × product combination.
--    Business Code: product_prefix + alpha → ZPNA01
--    Reference Code: ZEA01ZPNA01 (globally unique)
-- ============================================================
CREATE TABLE zi_subscriptions (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code           TEXT NOT NULL,                 -- ZPNA01 (unique within entity)
  entity_id         UUID NOT NULL REFERENCES zi_entities(id),
  ref_code          TEXT UNIQUE NOT NULL,          -- ZEA01ZPNA01 (globally unique)
  product_code      TEXT NOT NULL,                 -- ZPN | ZFLT | ZLD | ZFD | ZCR | ZPLS | ZND...
  product_name      TEXT NOT NULL,                 -- ZiPawn | ZiFleet...
  plan_type         TEXT NOT NULL DEFAULT 'trial', -- trial | solo | plus | pro
  status            TEXT NOT NULL DEFAULT 'trial', -- trial | active | paused | grace | cancelled
  trial_start       DATE,
  trial_end         DATE,
  billing_start     DATE,
  is_annual         BOOLEAN NOT NULL DEFAULT FALSE,
  max_users         INT,                           -- null = unlimited (pro)
  primary_owner_id  UUID REFERENCES zi_individuals(id),
  billing_owner_id  UUID REFERENCES zi_individuals(id),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, zi_code),
  CONSTRAINT chk_plan_type CHECK (plan_type IN ('trial','solo','plus','pro')),
  CONSTRAINT chk_status CHECK (status IN ('trial','active','paused','grace','cancelled'))
);

CREATE INDEX idx_subs_entity ON zi_subscriptions(entity_id);
CREATE INDEX idx_subs_product ON zi_subscriptions(product_code);

-- ============================================================
-- 7. zi_memberships
--    Individual ↔ Entity link with role.
--    Reference Code: ZEA01ZUA01 (entity_code + individual_code)
--    No own zi_code — the ref_code IS the identifier.
-- ============================================================
CREATE TABLE zi_memberships (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_code          TEXT UNIQUE NOT NULL,          -- ZEA01ZUA01 (entity_code + individual_code)
  entity_id         UUID NOT NULL REFERENCES zi_entities(id),
  individual_id     UUID NOT NULL REFERENCES zi_individuals(id),
  role              TEXT NOT NULL,                 -- owner | co_owner | partner | manager | staff | custom
  is_primary_owner  BOOLEAN NOT NULL DEFAULT FALSE,
  is_billing_owner  BOOLEAN NOT NULL DEFAULT FALSE,
  equity_percent    NUMERIC(5,2),                  -- for partners, co-owners
  permissions       JSONB,                         -- for custom roles
  branch_access     JSONB,                         -- array of branch ref_codes, null = all branches
  invited_by        UUID REFERENCES zi_individuals(id),
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  joined_at         TIMESTAMPTZ,
  expires_at        TIMESTAMPTZ,                   -- for temporary staff access
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, individual_id),
  CONSTRAINT chk_role CHECK (role IN ('owner','co_owner','partner','manager','staff','custom'))
);

-- Enforce: only one primary_owner and one billing_owner per entity
CREATE UNIQUE INDEX idx_memberships_primary_owner
  ON zi_memberships(entity_id)
  WHERE is_primary_owner = TRUE;

CREATE UNIQUE INDEX idx_memberships_billing_owner
  ON zi_memberships(entity_id)
  WHERE is_billing_owner = TRUE;

CREATE INDEX idx_memberships_entity ON zi_memberships(entity_id);
CREATE INDEX idx_memberships_individual ON zi_memberships(individual_id);

-- ============================================================
-- 8. zi_biz_contacts
--    People who interact WITH a business (customers, suppliers, etc.)
--    Always scoped to entity + product subscription.
--    Business Code: CST/SUP/VND/AGT/PTR + alpha → CSTA01
--    Reference Code: ZEA01ZPNA01CSTA01
-- ============================================================
CREATE TABLE zi_biz_contacts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zi_code          TEXT NOT NULL,                  -- CSTA01 (unique within entity+sub+type)
  ref_code         TEXT UNIQUE NOT NULL,           -- ZEA01ZPNA01CSTA01
  entity_id        UUID NOT NULL REFERENCES zi_entities(id),
  subscription_id  UUID NOT NULL REFERENCES zi_subscriptions(id),
  individual_id    UUID REFERENCES zi_individuals(id), -- null if walk-in / not on platform
  contact_type     TEXT NOT NULL,                  -- CST | SUP | VND | AGT | PTR
  display_name     TEXT NOT NULL,
  mobile_display   TEXT,                           -- last 4 digits cached
  email_display    TEXT,                           -- email cached for display
  tags             JSONB,                          -- flexible tagging
  is_verified      BOOLEAN NOT NULL DEFAULT FALSE,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(entity_id, subscription_id, contact_type, zi_code),
  CONSTRAINT chk_contact_type CHECK (contact_type IN ('CST','SUP','VND','AGT','PTR'))
);

CREATE INDEX idx_biz_contacts_entity ON zi_biz_contacts(entity_id);
CREATE INDEX idx_biz_contacts_sub ON zi_biz_contacts(subscription_id);
CREATE INDEX idx_biz_contacts_individual ON zi_biz_contacts(individual_id);

-- ============================================================
-- 9. zi_national_id_config
--    Country-specific ID configuration.
-- ============================================================
CREATE TABLE zi_national_id_config (
  country_code       TEXT PRIMARY KEY,
  country_name       TEXT NOT NULL,
  individual_id_name TEXT,                         -- Aadhaar, SSN, NRIC, Emirates ID
  individual_format  TEXT,                         -- regex for validation
  business_id_name   TEXT,                         -- GST, CIN, EIN, UEN
  business_format    TEXT,
  store_raw          BOOLEAN NOT NULL DEFAULT FALSE,
  store_hash         BOOLEAN NOT NULL DEFAULT TRUE,
  display_last       INT NOT NULL DEFAULT 6,
  verify_api         TEXT
);

-- Seed country configs
INSERT INTO zi_national_id_config VALUES
  ('IN', 'India',       'Aadhaar',    '^\d{12}$',              'GST/CIN/MSME', NULL,         FALSE, TRUE, 6, 'https://api.uidai.gov.in'),
  ('US', 'USA',         'SSN',        '^\d{9}$',               'EIN',          '^\d{9}$',    FALSE, TRUE, 6, NULL),
  ('AE', 'UAE',         'Emirates ID','^\d{15}$',              'Trade License', NULL,         FALSE, TRUE, 6, NULL),
  ('SG', 'Singapore',   'NRIC',       '^[STFG]\d{7}[A-Z]$',   'UEN',          NULL,         FALSE, TRUE, 6, NULL),
  ('GB', 'UK',          'NI Number',  '^[A-Z]{2}\d{6}[A-Z]$', 'Companies House', NULL,      FALSE, TRUE, 6, NULL),
  ('MY', 'Malaysia',    'MyKad',      '^\d{12}$',              'SSM',          NULL,         FALSE, TRUE, 6, NULL);
